Rails.application.routes.draw do
  root to: 'home#index'

  post '/admins/index',   to: 'admins#sign_in',    as: 'admin_sign_in'
  post '/admins/new',    to: 'admins#create'
  get '/admins/index',   to: 'admins#index'
  get '/admins/new',   to: 'admins#new'  
  get '/flashes/admin_panel',  to: 'flashes#admin_panel',    as: 'admin_profile'
  get '/admins/new',   to: 'admins#new'
  post '/admins/new',   to: 'admins#create',  as: 'admins'
  get '/home/index',   to: 'home#index', as: 'home'
  get '/profiles/student_show',   to: 'profiles#student_show'
  get '/students/new',   to: 'students#new'   
  get '/students/create',   to: 'students#student_show',    as: 'student_profile'
  post '/students/index',    to: 'students#sign_in'
  post '/students/new', to: 'students#create',    as: 'student_new' 
  get '/students/index', to: 'students#index',    as: 'student_home' 
  get '/dashboard/teacher_profile', to: 'dashboard#teacher_profile',  as: 'instructor'
  get '/teachers/index', to: 'teachers#index',    as: 'teacher_home' 
  get '/teachers/new',   to: 'teachers#new',   as: 'teachers_path'
  post '/teachers/index',   to: 'teachers#sign_in',   as: 'teacher_signin'
  post '/teachers/new', to: 'teachers#create',    as: 'create_teacher'
  post '/cohorts/index',   to: 'cohorts#index'
  post '/cohorts/new',   to:   'cohorts#create'
  get '/cohorts/new',    to: 'cohorts#new'
  post '/Courses/new',   to: 'courses#create',   as: 'courses'
  get '/courses/new',    to: 'courses#new'
  get '/courses/index',    to: 'courses#index'
end
